model: 'elan'
## parameters for plain
scale: 3
rgb_range: 255
colors: 3
#m_elan: 24
#c_elan: 60
m_elan: 16
c_elan: 48
n_share: 1
r_expand: 2
act_type: 'relu'
window_sizes: [4, 8, 16]
pretrain:

## parameters for model training
#patch_size: 256
patch_size: 63
#batch_size: 64
batch_size: 32
data_repeat: 80
data_augment: 1

#epochs: 1000
epochs : 120
lr: 0.0002
#decays: [250, 400, 450, 475, 500]
decays: [50, 80, 90, 95, 100]
gamma: 0.5
log_every: 100
test_every: 1
log_path: "./experiments_v2"
log_name:

## hardware specification
gpu_ids: [0]
threads: 2

## data specification
#data_path: '/home/xindongzhang/SR_datasets'
data_path: '../'
eval_sets: ['Set5', 'Set14', 'B100']